AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: go-serverless-lambda-apigw-offline-skeleton
Globals:
  Function:
    Runtime: go1.x
    Timeout: 180
    
Resources:
  Connection:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: connect
      Events:
        ConnectionHandler:
          Type: Api
          Properties:
            Path: /.netlify/functions/connection
            Method: get
  Form:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: form
      Events:
        FormHandler:
          Type: Api
          Properties:
            Path: /.netlify/functions/form
            Method: post
  Apigw:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: apigw
      Events:
        APIGWHandler:
          Type: Api
          Properties:
            Path: /.netlify/functions/apigw
            Method: get
