AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: go-serverless-lambda-apigw-offline-skeleton
Globals:
  Function:
    Runtime: go1.x
    Timeout: 180
    Environment:
      Variables:
        ENV_KEY: SOMELOCALKEY
        
Resources:
  Connection:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: connect
      Events:
        ConnectionHandler:
          Type: Api
          Properties:
            Path: /.netlify/functions/connection
            Method: get
  Form:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: form
      Events:
        FormHandler:
          Type: Api
          Properties:
            Path: /.netlify/functions/form
            Method: post
  ENV:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: env
      Events:
        EnvHandler:
          Type: Api
          Properties:
            Path: /.netlify/functions/env
            Method: any
  API:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: crypto
      Events:
        FormHandler:
          Type: Api
          Properties:
            Path: /.netlify/functions/crypto
            Method: any
